# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BackTaskApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v3
      with:        
        username: ${{ secrets.AzureAppService_ContainerUsername_704b997558b14a43abf8573cf25cc773 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_48bfdf78a72a4240a83b0b032044b66f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_704b997558b14a43abf8573cf25cc773 }}/taskapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BackTaskApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_40971ce730414ec7bca3171b205de41b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_704b997558b14a43abf8573cf25cc773 }}/taskapp:${{ github.sha }}'
